// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMm5i7VqOh1xxVyi4ldNc_fZNg4dc8TN8',
    appId: '1:181443198732:web:27f4fa5238e29de97a9329',
    messagingSenderId: '181443198732',
    projectId: 'movie-list-app-1a05a',
    authDomain: 'movie-list-app-1a05a.firebaseapp.com',
    storageBucket: 'movie-list-app-1a05a.appspot.com',
    measurementId: 'G-C2JNHZJVCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrX0oLny9gDhwhmM09wAGoGXsrSVUN-8',
    appId: '1:181443198732:android:439ddc8a62978b547a9329',
    messagingSenderId: '181443198732',
    projectId: 'movie-list-app-1a05a',
    storageBucket: 'movie-list-app-1a05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1bA5IFh23MNEYIIqGcwlzWRADonlinv4',
    appId: '1:181443198732:ios:27d7ef2482bff7ad7a9329',
    messagingSenderId: '181443198732',
    projectId: 'movie-list-app-1a05a',
    storageBucket: 'movie-list-app-1a05a.appspot.com',
    iosClientId: '181443198732-hkvfql5fsedqnm2jf1pquktro13g0paf.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1bA5IFh23MNEYIIqGcwlzWRADonlinv4',
    appId: '1:181443198732:ios:27d7ef2482bff7ad7a9329',
    messagingSenderId: '181443198732',
    projectId: 'movie-list-app-1a05a',
    storageBucket: 'movie-list-app-1a05a.appspot.com',
    iosClientId: '181443198732-hkvfql5fsedqnm2jf1pquktro13g0paf.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieListApp',
  );
}
